[mappings]
move_up = "up"
move_down = "down"
expand_node = "right"
collapse_node = "left"
open_node = "enter"
exit_fullscreen_preview = "esc"
switch_focus = "tab"
page_up = "pageup"
page_down = "pagedown"
preview_scroll_up = "'"
preview_scroll_down = "/"
toggle_preview_line_numbers = "l"
toggle_preview_wrap = "w"
toggle_help = "?"
toggle_hidden = "h"
quit = "q"
